### ISSUE TITLE
[BUG] - Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by rafacrudi** [PwQt/magic-items-2#65] opened 2024-02-15 19:28 UTC
**Foundry Version:** v11.315
**System Version:** D&D 5e v3.0.2
**Module Version:** v1.6.1

**Before open any issue**

*** 1) I don't see a  _"Enable debugging"_ option to be enabled. ***
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

This is what the log shows:
foundry.js:68326 Cannot read properties of null (reading 'parent')
[Detected 1 package: system:dnd5e]
fetch	@	foundry.js:68326

**Describe the bug**
When trying to cast a spell on multiple targets, got the above message on the console: "Cannot read properties of null (reading 'parent') [Detected 1 package: system:dnd5e]"

**To Reproduce**
1. Marked an item as "is magic item"
2. Added spell "Bless" at 3rd level (5 targets)
3. Spell shows in Character sheet.
4. Clicked on the spell
5. Selected the tokens
6. In Spell card, clicked "Apply to selected tokens"
7. Effect didn't apply, saw the error message.

**Expected behavior**
Well, spell should be applied to the target without the error.
The character is a Claric with the spell on his list, I can cast it on the same targets, no problem.

**Screenshots**

**Browser:**
 - Directly on Foundry
![Cannot read properties of null parent - Magic Item details](https://github.com/PwQt/magic-items-2/assets/74941182/dd3e94ef-1607-416d-b835-3d1de6f42665)
![Cannot read properties of null parent](https://github.com/PwQt/magic-items-2/assets/74941182/1ff7e7e2-4a74-4761-97d1-101827f8bdb8)

**Comment by PwQt** [comment] 2024-02-15 19:45
Duplicate of #63

**Closed by PwQt** 2024-02-15 19:45 UTC
Labels: bug
